In [1]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = np.copy(A)
    for k in range(n - 1):
        for i in range(k + 1, n):
            if U[k, k] == 0:
                raise ValueError("Matrix is singular (division by zero).")
            L[i, k] = U[i, k] / U[k, k]
            for j in range(k, n):
                U[i, j] -= L[i, k] * U[k, j]
    return L, U

A = np.array([[2, -1, -2],
              [-4, 6, 3],
              [-4, -2, 8]])

L, U = lu_decomposition(A)
print("Lower triangular matrix L:\n", L)
print("Upper triangular matrix U:\n", U)


Lower triangular matrix L:
 [[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]
Upper triangular matrix U:
 [[ 2 -1 -2]
 [ 0  4 -1]
 [ 0  0  3]]


In [2]:
# Verify that A = L * U
A_reconstructed = np.dot(L, U)
print("Reconstructed A:\n", A_reconstructed)

Reconstructed A:
 [[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]


In [3]:
def forward_substitution(L, b):
    """
    Solve L * y = b for y using forward substitution.
    """
    n = len(L)
    print(y)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y

In [4]:
def backward_substitution(U, y):
    """
    Solve U * x = y for x using backward substitution.
    """
    n = len(U)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x

In [6]:
import numpy as np

def forward_substitution(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y

def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in reversed(range(n)):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

b = np.array([1, 2, 3])

y = forward_substitution(L, b)
x = backward_substitution(U, y)

print("Solution x:\n", x)


Solution x:
 [4.375 1.75  3.   ]
